CREATE TABLE IF NOT EXISTS Account (
  ID VARCHAR(50) PRIMARY KEY,
  PasswordHash VARCHAR(64) NOT NULL,
  Salt VARCHAR(32) NOT NULL,
  Iterations INTEGER NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Role VARCHAR(50) NOT NULL DEFAULT 'user'
);
